Add typescript for native
mendix/Atlas-theme-default pull request #48
Opened 2020-03-12 11:36 UTC by wesleysieses

2020-03-12 16:20 UTC, diego-antonelli requested changes

2020-03-12 16:20 UTC, diego-antonelli commented on styles/native/ts/core/helpers/_functions/convertcolors.ts
> +function RgbToHex(r: string | number, g: string | number | undefined, b: string | number | undefined): string {
Extract string | number in an interface, g and b can be optional

2020-03-12 16:20 UTC, diego-antonelli commented on styles/native/ts/core/helpers/_functions/convertcolors.ts
> +    let h: string | number = hslArray[0],
Extract string | number to reuse

2020-03-13 10:54 UTC, diego-antonelli submitted a review, later dismissed

2020-03-17 12:01 UTC, diego-antonelli submitted a review, later dismissed

2020-03-17 16:35 UTC, diego-antonelli submitted a review, later dismissed

2020-04-01 11:44 UTC, mmehmetAliIzci approved these changes

2020-04-01 11:45 UTC, merged